begin;
set role app_loto_owner;

-- pgls-ignore-start lint/safety/banDropTable
drop table if exists work.raw1, work.raw2, work.raw34, work.raw5;
-- pgls-ignore-end lint/safety/banDropTable

-- staging tables in work
--
create table work.raw1(
    annee_numero_de_tirage text,
    "1er_ou_2eme_tirage" text,
    jour_de_tirage text,
    date_de_tirage text,
    date_de_forclusion text,
    boule_1 text,
    boule_2 text,
    boule_3 text,
    boule_4 text,
    boule_5 text,
    boule_6 text,
    boule_complementaire text,
    combinaison_gagnante_en_ordre_croissant text,
    numero_joker text,
    nombre_de_gagnant_au_rang1 text,
    rapport_du_rang1 text,
    nombre_de_gagnant_au_rang2 text,
    rapport_du_rang2 text,
    nombre_de_gagnant_au_rang3 text,
    rapport_du_rang3 text,
    nombre_de_gagnant_au_rang4 text,
    rapport_du_rang4 text,
    nombre_de_gagnant_au_rang5 text,
    rapport_du_rang5 text,
    nombre_de_gagnant_au_rang6 text,
    rapport_du_rang6 text,
    nombre_de_gagnant_au_rang7 text,
    rapport_du_rang7 text,
    numero_jokerplus text,
    devise text,
    trailing_empty text
);
create table work.raw2(
    annee_numero_de_tirage text,
    jour_de_tirage text,
    date_de_tirage text,
    date_de_forclusion text,
    boule_1 text,
    boule_2 text,
    boule_3 text,
    boule_4 text,
    boule_5 text,
    numero_chance text,
    combinaison_gagnante_en_ordre_croissant text,
    nombre_de_gagnant_au_rang1 text,
    rapport_du_rang1 text,
    nombre_de_gagnant_au_rang2 text,
    rapport_du_rang2 text,
    nombre_de_gagnant_au_rang3 text,
    rapport_du_rang3 text,
    nombre_de_gagnant_au_rang4 text,
    rapport_du_rang4 text,
    nombre_de_gagnant_au_rang5 text,
    rapport_du_rang5 text,
    nombre_de_gagnant_au_rang6 text,
    rapport_du_rang6 text,
    numero_jokerplus text,
    devise text,
    -- les lignes finissent par un ';' (champ vide terminal)
    trailing_empty text
);
create table work.raw34(
    annee_numero_de_tirage text,
    jour_de_tirage text,
    date_de_tirage text,
    date_de_forclusion text,
    boule_1 text,
    boule_2 text,
    boule_3 text,
    boule_4 text,
    boule_5 text,
    numero_chance text,
    combinaison_gagnante_en_ordre_croissant text,
    nombre_de_gagnant_au_rang1 text,
    rapport_du_rang1 text,
    nombre_de_gagnant_au_rang2 text,
    rapport_du_rang2 text,
    nombre_de_gagnant_au_rang3 text,
    rapport_du_rang3 text,
    nombre_de_gagnant_au_rang4 text,
    rapport_du_rang4 text,
    nombre_de_gagnant_au_rang5 text,
    rapport_du_rang5 text,
    nombre_de_gagnant_au_rang6 text,
    rapport_du_rang6 text,
    nombre_de_gagnant_au_rang7 text,
    rapport_du_rang7 text,
    nombre_de_gagnant_au_rang8 text,
    rapport_du_rang8 text,
    nombre_de_gagnant_au_rang9 text,
    rapport_du_rang9 text,
    nombre_de_codes_gagnants text,
    rapport_codes_gagnants text,
    codes_gagnants text,
    numero_jokerplus text,
    devise text,
    -- les lignes finissent par un ';' (champ vide terminal)
    trailing_empty text
);
create table work.raw5(
    annee_numero_de_tirage text,
    jour_de_tirage text,
    date_de_tirage text,
    date_de_forclusion text,
    boule_1 text,
    boule_2 text,
    boule_3 text,
    boule_4 text,
    boule_5 text,
    numero_chance text,
    combinaison_gagnante_en_ordre_croissant text,
    nombre_de_gagnant_au_rang1 text,
    rapport_du_rang1 text,
    nombre_de_gagnant_au_rang2 text,
    rapport_du_rang2 text,
    nombre_de_gagnant_au_rang3 text,
    rapport_du_rang3 text,
    nombre_de_gagnant_au_rang4 text,
    rapport_du_rang4 text,
    nombre_de_gagnant_au_rang5 text,
    rapport_du_rang5 text,
    nombre_de_gagnant_au_rang6 text,
    rapport_du_rang6 text,
    nombre_de_gagnant_au_rang7 text,
    rapport_du_rang7 text,
    nombre_de_gagnant_au_rang8 text,
    rapport_du_rang8 text,
    nombre_de_gagnant_au_rang9 text,
    rapport_du_rang9 text,
    nombre_de_codes_gagnants text,
    rapport_codes_gagnants text,
    codes_gagnants text,
    boule_1_second_tirage text,
    boule_2_second_tirage text,
    boule_3_second_tirage text,
    boule_4_second_tirage text,
    boule_5_second_tirage text,
    promotion_second_tirage text,
    combinaison_gagnant_second_tirage_en_ordre_croissant text,
    nombre_de_gagnant_au_rang_1_second_tirage text,
    rapport_du_rang1_second_tirage text,
    nombre_de_gagnant_au_rang_2_second_tirage text,
    rapport_du_rang2_second_tirage text,
    nombre_de_gagnant_au_rang_3_second_tirage text,
    rapport_du_rang3_second_tirage text,
    nombre_de_gagnant_au_rang_4_second_tirage text,
    rapport_du_rang4_second_tirage text,
    numero_jokerplus text,
    devise text,
    trailing_empty text
);

reset role;
commit;
